/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProntoPagoRouteImport } from './routes/pronto-pago'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasosModalidadRouteImport } from './routes/pasos.$modalidad'
import { Route as MatriculaSlugRouteImport } from './routes/matricula.$slug'

const ProntoPagoRoute = ProntoPagoRouteImport.update({
  id: '/pronto-pago',
  path: '/pronto-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasosModalidadRoute = PasosModalidadRouteImport.update({
  id: '/pasos/$modalidad',
  path: '/pasos/$modalidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaSlugRoute = MatriculaSlugRouteImport.update({
  id: '/matricula/$slug',
  path: '/matricula/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pronto-pago': typeof ProntoPagoRoute
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/pasos/$modalidad': typeof PasosModalidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pronto-pago': typeof ProntoPagoRoute
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/pasos/$modalidad': typeof PasosModalidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pronto-pago': typeof ProntoPagoRoute
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/pasos/$modalidad': typeof PasosModalidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pronto-pago' | '/matricula/$slug' | '/pasos/$modalidad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pronto-pago' | '/matricula/$slug' | '/pasos/$modalidad'
  id:
    | '__root__'
    | '/'
    | '/pronto-pago'
    | '/matricula/$slug'
    | '/pasos/$modalidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProntoPagoRoute: typeof ProntoPagoRoute
  MatriculaSlugRoute: typeof MatriculaSlugRoute
  PasosModalidadRoute: typeof PasosModalidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pronto-pago': {
      id: '/pronto-pago'
      path: '/pronto-pago'
      fullPath: '/pronto-pago'
      preLoaderRoute: typeof ProntoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasos/$modalidad': {
      id: '/pasos/$modalidad'
      path: '/pasos/$modalidad'
      fullPath: '/pasos/$modalidad'
      preLoaderRoute: typeof PasosModalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula/$slug': {
      id: '/matricula/$slug'
      path: '/matricula/$slug'
      fullPath: '/matricula/$slug'
      preLoaderRoute: typeof MatriculaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProntoPagoRoute: ProntoPagoRoute,
  MatriculaSlugRoute: MatriculaSlugRoute,
  PasosModalidadRoute: PasosModalidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
