/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasosModalidadRouteImport } from './routes/pasos.$modalidad'
import { Route as MatriculaSlugRouteImport } from './routes/matricula.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasosModalidadRoute = PasosModalidadRouteImport.update({
  id: '/pasos/$modalidad',
  path: '/pasos/$modalidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaSlugRoute = MatriculaSlugRouteImport.update({
  id: '/matricula/$slug',
  path: '/matricula/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/pasos/$modalidad': typeof PasosModalidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/pasos/$modalidad': typeof PasosModalidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/pasos/$modalidad': typeof PasosModalidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matricula/$slug' | '/pasos/$modalidad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matricula/$slug' | '/pasos/$modalidad'
  id: '__root__' | '/' | '/matricula/$slug' | '/pasos/$modalidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatriculaSlugRoute: typeof MatriculaSlugRoute
  PasosModalidadRoute: typeof PasosModalidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasos/$modalidad': {
      id: '/pasos/$modalidad'
      path: '/pasos/$modalidad'
      fullPath: '/pasos/$modalidad'
      preLoaderRoute: typeof PasosModalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula/$slug': {
      id: '/matricula/$slug'
      path: '/matricula/$slug'
      fullPath: '/matricula/$slug'
      preLoaderRoute: typeof MatriculaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatriculaSlugRoute: MatriculaSlugRoute,
  PasosModalidadRoute: PasosModalidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
