/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProntoPagoRouteImport } from './routes/pronto-pago'
import { Route as IndexRouteImport } from './routes/index'

const ProntoPagoRoute = ProntoPagoRouteImport.update({
  id: '/pronto-pago',
  path: '/pronto-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pronto-pago': typeof ProntoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pronto-pago': typeof ProntoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pronto-pago': typeof ProntoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pronto-pago'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pronto-pago'
  id: '__root__' | '/' | '/pronto-pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProntoPagoRoute: typeof ProntoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pronto-pago': {
      id: '/pronto-pago'
      path: '/pronto-pago'
      fullPath: '/pronto-pago'
      preLoaderRoute: typeof ProntoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProntoPagoRoute: ProntoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
